import type { RuntimeManifest } from '../../../config/RuntimeManifest.js';

export interface LiteLlmModelEntry {
  model_name: string;
  litellm_params: Record<string, unknown>;
}

export interface LiteLlmConfig {
  model_list: LiteLlmModelEntry[];
  litellm_settings: Record<string, unknown>;
}

export interface DeploymentForConfig {
  id: string;
  gatewayId: string;
  secretRef: string;
  providerModelId: string;
  logicalId: string;
  baseUrl: string;
  protocol: string;
}

export class LiteLlmConfigAdapter {
  generate(manifest: RuntimeManifest, deployments: DeploymentForConfig[]): LiteLlmConfig {
    const modelList = this.buildModelList(manifest, deployments);
    return {
      model_list: modelList,
      litellm_settings: {
        drop_params: true,
        set_verbose: false,
        num_retries: 0,
      },
    };
  }

  toYaml(config: LiteLlmConfig): string {
    const lines: string[] = [];
    lines.push('# Generated by LiteLlmConfigAdapter — do not edit manually');
    lines.push(`# generatedAt: ${new Date().toISOString()}`);
    lines.push('model_list:');
    for (const m of config.model_list) {
      lines.push(`  - model_name: ${yamlEscape(String(m.model_name))}`);
      lines.push('    litellm_params:');
      for (const [k, v] of Object.entries(m.litellm_params)) {
        lines.push(`      ${k}: ${yamlValue(v)}`);
      }
    }
    lines.push('litellm_settings:');
    for (const [k, v] of Object.entries(config.litellm_settings)) {
      lines.push(`  ${k}: ${yamlValue(v)}`);
    }
    return lines.join('\n') + '\n';
  }

  private buildModelList(manifest: RuntimeManifest, deployments: DeploymentForConfig[]): LiteLlmModelEntry[] {
    const endpointByGw = new Map(manifest.endpoints.map((e: { gateway_id: string; protocol: string }) => [e.gateway_id + ':' + e.protocol, e]));
    return deployments.map((d) => {
      const ep = endpointByGw.get(d.gatewayId + ':' + d.protocol) as { base_url: string } | undefined;
      const fallback = manifest.endpoints.find((e: { gateway_id: string }) => e.gateway_id === d.gatewayId) as { base_url: string } | undefined;
      const base = ep?.base_url ?? fallback?.base_url ?? d.baseUrl;
      return {
        model_name: d.logicalId,
        litellm_params: {
          model: d.providerModelId,
          api_base: base,
          api_key: `os.environ/${d.secretRef}`,
        },
      };
    });
  }
}

function yamlEscape(s: string): string {
  if (/[:#\n]/.test(s)) return JSON.stringify(s);
  return s;
}

function yamlValue(v: unknown): string {
  if (typeof v === 'string') return yamlEscape(v);
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  return JSON.stringify(v);
}
